"""Every lead table has a hand-written section in `docs/TABLES.md`, and every section names a real table.

**Why a test.** `docs/TABLES.md` carries the half of the per-table reference a model cannot state — the
grain of a row, which cells a person decides, why the artifact has its shape, the symptom when the table
is wrong. The columns beside it are generated on every build and cannot go stale; the prose can, and the
way it goes stale is by *omission*: a table kind is added, its page is generated by construction, and
nobody notices that the page has no prose because the site still looks complete. That is the same
mechanism that left `just-module-creator`'s dossiers a release behind, with two 0.7 table kinds carrying
no entry at all.

**The assertion is asymmetric, deliberately** — `authored ⊆ sections ⊆ all tables`, never an equality. A
section for a *derived* table is legal and welcome: those get prose when somebody has something to say,
which is the "on demand" half of the decision, and an equality would refuse it.

**The required set is `DRAFTABLE`, and it started as `LEAD_PARQUETS` — which was wrong.** A peer session
grepped its task-shaped guides and reported that `studies.csv` and `overrides.csv` appear in neither
theirs nor the prose, and the overlay is a *cell-authorship* question, which is precisely what
`TABLES.md` is for. `LEAD_PARQUETS` describes what a consumer reads first; *who writes which cell*
describes what a person writes at all. Different sets, and `overrides.csv`, `studies.csv` and
`licensing.csv` are the three that fell between them.

`@registry-completeness` in its asymmetric form: assert the containment over a walked set, never a count.
"""

import re
from pathlib import Path

import just_dna_compiler.compiler as C
from just_dna_compiler.draft import DRAFTABLE
from just_dna_compiler.hints import DERIVED_TABLE_MODELS
from just_dna_format.layout import DEPRECATED_SPELLINGS, sidecar_key

_PROSE = Path(__file__).resolve().parents[2] / "docs" / "TABLES.md"

#: `## <something>.csv` at the start of a line — the same split `scripts/gen_table_pages.py` uses to
#: slice the file, so the two cannot disagree about what counts as a section.
_SECTION = re.compile(r"^## +(\S+\.csv)\s*$", re.MULTILINE)


def _sections() -> set[str]:
    return set(_SECTION.findall(_PROSE.read_text(encoding="utf-8")))


def _authored_tables() -> set[str]:
    """The tables a person writes — `DRAFTABLE`, normalised to the spelling a page is written under.

    Walked rather than listed, and normalised rather than filtered: `DRAFTABLE` carries both spellings of
    the licence table, and the page exists under the current one only, so a raw set would demand a
    section for a name the generator never writes (`@sidecar-name-and-place`).
    """
    return {sidecar_key(csv) for csv in DRAFTABLE}


def test_every_authored_table_has_prose() -> None:
    missing = sorted(_authored_tables() - {sidecar_key(s) for s in _sections()})
    assert not missing, (
        "these authored tables have a generated reference page with no hand-written section above it, so "
        "the page states the columns and never says what a row is or who decides which cell: add a "
        f"`## <name>.csv` section to docs/TABLES.md for each of {missing}"
    )


def test_the_lead_tables_are_a_subset_of_the_authored_ones() -> None:
    """The containment that makes the widened requirement strictly stronger than the old one.

    Asserted rather than assumed, because the requirement was changed *from* `LEAD_PARQUETS` *to*
    `DRAFTABLE` and "stronger" is the claim that justified the change. If a lead table ever stops being
    authored, this fails and the prose requirement needs re-deciding rather than silently narrowing.
    """
    lead = {
        csv
        for csv, parquets in C.table_bindings().items()
        if any(parquet in C.LEAD_PARQUETS for parquet in parquets)
    }
    assert lead <= _authored_tables(), (
        "these tables produce a lead parquet but are not authored, so widening the prose requirement to "
        f"`DRAFTABLE` silently dropped them: {sorted(lead - _authored_tables())}"
    )


def test_no_section_names_a_table_that_does_not_exist() -> None:
    """A section for a renamed or removed table is prose nothing splices — invisible on the site."""
    known = {sidecar_key(csv) for csv in {*DRAFTABLE, *DERIVED_TABLE_MODELS}}
    unknown = sorted(csv for csv in _sections() if sidecar_key(csv) not in known)
    assert not unknown, (
        f"docs/TABLES.md has sections for tables no registry knows: {unknown}. A renamed table leaves "
        "its prose orphaned, and nothing on the site shows the absence"
    )


def test_no_section_uses_a_deprecated_spelling() -> None:
    """Prose is keyed on the name the page is written under, which is the current spelling.

    `gen_table_pages.py` drops `DEPRECATED_SPELLINGS` when choosing page names, so a `## sources.csv`
    section would be spliced into nothing — the same silent-omission failure this file exists to catch,
    one spelling over (`@sidecar-name-and-place`).
    """
    deprecated = sorted(_sections() & DEPRECATED_SPELLINGS)
    assert not deprecated, (
        f"these sections use a deprecated spelling and would splice into no page: {deprecated}. Use the "
        "current name — the page names the deprecated one in its identity card"
    )
