"""Every lead table has a hand-written section in `docs/TABLES.md`, and every section names a real table.

**Why a test.** `docs/TABLES.md` carries the half of the per-table reference a model cannot state — the
grain of a row, which cells a person decides, why the artifact has its shape, the symptom when the table
is wrong. The columns beside it are generated on every build and cannot go stale; the prose can, and the
way it goes stale is by *omission*: a table kind is added, its page is generated by construction, and
nobody notices that the page has no prose because the site still looks complete. That is the same
mechanism that left `just-module-creator`'s dossiers a release behind, with two 0.7 table kinds carrying
no entry at all.

**The assertion is asymmetric, deliberately** — `lead ⊆ sections ⊆ all tables`, never an equality. The
lead tables (whose parquet is in `LEAD_PARQUETS`) are the ones an author writes by hand, so a missing
section there is a real gap. A section for any *other* table is legal and welcome: the derived tables get
prose when somebody has something to say, which is the "on demand" half of the decision, and an equality
would refuse it.

`@registry-completeness` in its asymmetric form: assert the containment over a walked set, never a count.
"""

import re
from pathlib import Path

import just_dna_compiler.compiler as C
from just_dna_compiler.draft import DRAFTABLE
from just_dna_compiler.hints import DERIVED_TABLE_MODELS
from just_dna_format.layout import DEPRECATED_SPELLINGS, sidecar_key

_PROSE = Path(__file__).resolve().parents[2] / "docs" / "TABLES.md"

#: `## <something>.csv` at the start of a line — the same split `scripts/gen_table_pages.py` uses to
#: slice the file, so the two cannot disagree about what counts as a section.
_SECTION = re.compile(r"^## +(\S+\.csv)\s*$", re.MULTILINE)


def _sections() -> set[str]:
    return set(_SECTION.findall(_PROSE.read_text(encoding="utf-8")))


def _lead_tables() -> set[str]:
    """The CSVs whose parquet is a lead parquet — derived, because `variants.csv` is the tenth.

    Not a list: `LEAD_PARQUETS` holds the nine table kinds' parquets plus `weights.parquet`, and
    `weights` comes from `variants.csv` through `SNP_CORE_PARQUETS`. Spelling the ten out here would
    hand-keep exactly the roster the binding exists to derive.
    """
    return {
        csv
        for csv, parquets in C.table_bindings().items()
        if any(parquet in C.LEAD_PARQUETS for parquet in parquets)
    }


def test_every_lead_table_has_prose() -> None:
    missing = sorted(_lead_tables() - _sections())
    assert not missing, (
        "these lead tables have a generated reference page with no hand-written section above it, so "
        "the page states the columns and never says what a row is: add a `## <name>.csv` section to "
        f"docs/TABLES.md for each of {missing}"
    )


def test_no_section_names_a_table_that_does_not_exist() -> None:
    """A section for a renamed or removed table is prose nothing splices — invisible on the site."""
    known = {sidecar_key(csv) for csv in {*DRAFTABLE, *DERIVED_TABLE_MODELS}}
    unknown = sorted(csv for csv in _sections() if sidecar_key(csv) not in known)
    assert not unknown, (
        f"docs/TABLES.md has sections for tables no registry knows: {unknown}. A renamed table leaves "
        "its prose orphaned, and nothing on the site shows the absence"
    )


def test_no_section_uses_a_deprecated_spelling() -> None:
    """Prose is keyed on the name the page is written under, which is the current spelling.

    `gen_table_pages.py` drops `DEPRECATED_SPELLINGS` when choosing page names, so a `## sources.csv`
    section would be spliced into nothing — the same silent-omission failure this file exists to catch,
    one spelling over (`@sidecar-name-and-place`).
    """
    deprecated = sorted(_sections() & DEPRECATED_SPELLINGS)
    assert not deprecated, (
        f"these sections use a deprecated spelling and would splice into no page: {deprecated}. Use the "
        "current name — the page names the deprecated one in its identity card"
    )
